#!/usr/bin/env python3
import sys
import cs50
import nltk

from nltk import TweetTokenizer
from helpers import *
from analyzer import Analyzer
from termcolor import colored

def main():
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets handle")

    tweet_list = get_user_timeline(sys.argv[1], count=5)


    if tweet_list == None:
            sys.exit("Couldn't get user timeline: Invalid twitter handle")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    for i in tweet_list:
        analyzer = Analyzer(positives, negatives)

        totalsum=analyzer.analyze(i)
        if totalsum>0:
            print(colored("{} {}".format(totalsum, i), "green"))
        elif totalsum<0:
            print(colored("{} {}".format(totalsum, i), "red"))
        else:
            print(colored("{} {}".format(totalsum, i), "yellow"))
if __name__ == "__main__":
    main()